# Generated by Django 5.2.6 on 2025-10-13 10:13

# Generated by Django 5.2.6 on 2025-10-13 10:03

import django.db.models.deletion
from django.db import migrations, models


def create_default_chat(apps, schema_editor):
    Chat = apps.get_model("chat", "Chat")
    User = apps.get_model("users", "CustomUser")  # или твоя модель пользователя
    first_user = User.objects.first()
    if first_user:
        chat = Chat.objects.create()
        chat.participants.add(first_user)
        chat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_created_at_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_chat),  # создаем дефолтный чат

        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(
                default=1,  # id созданного дефолтного чата
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to='chat.chat',
            ),
            preserve_default=False,
        ),
    ]
